name: Locust load testing

on: [workflow_dispatch]

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Azure CLI
        run: pip3 install azure-cli
      - name: Install Locust Load Test Tool
        run: pip3 install locust
      - name: Run Load Test
        run: locust -f ./LoadTest/locust.py --headless -u 1 -r 1 --run-time 10s -H https://20.107.65.156/
